SKILLS = [
    "python",
    "javascript",
    "typescript",
    "php",
    "java",
    "c++",
    "sql",
    "mysql",
    "postgresql",
    "mongodb",
    "html",
    "css",
    "react",
    "vue",
    "angular",
    "node.js",
    "fastapi",
    "django",
    "flask",
    "laravel",
    "git",
    "docker",
    "kubernetes",
    "aws",
    "azure",
    "machine learning",
    "deep learning",
    "nlp",
    "computer vision",
    "opencv",
    "mediapipe",
    "tensorflow",
    "pytorch",
    "pandas",
    "numpy",
    "scikit-learn",
    "rest api",
    "graphql",
    "rfid",
    "linux",
    "communication",
    "leadership",
    "project management",
]